# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ec9e88534f8971b1e95aba0d21092bf69459ad15f3344df59a67343adebd020a843f5c205d3f6fdcd4e257031490eb151cf1a06b7f5caea733222d230a39eec

test:
  secret_key_base: 8f5c3a9bf412205fbcd72e7de62b95eae6240aee7f43fbb14421e60e605c45ecb50bb9fc7ded74007450a1e29b555a24325f7f519b9d844437a1ea8b76d0e3fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
